### ISSUE TITLE
How to preprocess the wav files?

### ISSUE THREAD

**Issue by auzxb** [sannawag/autotuner#1]
Great work!! Would you please offer the code about how to generate such .npy files from my own .wav files?
```
        performance_list = sorted(list(
            set([f[:-4] for f in os.listdir(pyin_directory) if "npy"]) &
            set([f[:-4] for f in os.listdir(midi_directory) if "npy"]) &
            set([f[:-4] for f in os.listdir(back_chroma_directory) if "npy"])))
```

**Comment by sannawag** [comment]
Thank you!! Please check the updated README that references how to use Sonic Annotator as one option to get the pitch analysis. The new file interpolate_pyin.py will process the result and prepare it for the analysis. Just let me know if you have any questions!

**Comment by auzxb** [comment]
OK, thank you for your sharing! I'll work on this code and do some other experiments, such as the sing can't keep up the beat.
